/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.produtosDao;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Endereco;
import model.Fornecedores;
import model.Produtos;


/**
 *
 * @author Luciana_2
 */
public class CadProdutos extends javax.swing.JInternalFrame {
    private Principal telaAnterior;

    /**
     * Creates new form CadProdutos
     */
    public CadProdutos() {
        initComponents();
    }
    
    
    public CadProdutos(Principal telaAnterior){
        this();
        //construtor
        this.telaAnterior = telaAnterior;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelCP = new javax.swing.JLabel();
        jTextFieldCP = new javax.swing.JTextField();
        jLabelNP = new javax.swing.JLabel();
        jTextFieldNP = new javax.swing.JTextField();
        jLabelDP = new javax.swing.JLabel();
        jTextFieldDP = new javax.swing.JTextField();
        jLabelVP = new javax.swing.JLabel();
        jTextFieldVP = new javax.swing.JTextField();
        jLabelTP = new javax.swing.JLabel();
        jTextFieldPT = new javax.swing.JTextField();
        jButtonCadastrarProd = new javax.swing.JButton();
        jButtonCancelarProd = new javax.swing.JButton();
        jLabelNF = new javax.swing.JLabel();
        jTextFieldNF = new javax.swing.JTextField();
        jTextFieldQ = new javax.swing.JTextField();
        jLabelQ = new javax.swing.JLabel();

        setTitle("Cadastro de Produtos");

        jLabelCP.setText("Código do Produto: ");

        jTextFieldCP.setToolTipText("Informe o código do produto");

        jLabelNP.setText("Nome:");

        jTextFieldNP.setToolTipText("Informe o nome do produto");

        jLabelDP.setText("Descrição: ");

        jTextFieldDP.setToolTipText("Descreva o produto");

        jLabelVP.setText("Valor :");

        jTextFieldVP.setToolTipText("Informe o valor");

        jLabelTP.setText("Tipo:");

        jTextFieldPT.setToolTipText("Informe o tipo");

        jButtonCadastrarProd.setText("Cadastrar");
        jButtonCadastrarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarProdActionPerformed(evt);
            }
        });

        jButtonCancelarProd.setText("Cancelar");
        jButtonCancelarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarProdActionPerformed(evt);
            }
        });

        jLabelNF.setText("Nome do Fornecedor:");

        jLabelQ.setText("Quantidade:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelCP)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldCP, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelNP)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldNP, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelVP)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldVP, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelTP)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldPT)))
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelQ)
                                    .addComponent(jTextFieldQ, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(110, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelDP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldDP))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelNF))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTextFieldNF, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jButtonCadastrarProd, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jButtonCancelarProd, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCP)
                    .addComponent(jTextFieldCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNP)
                    .addComponent(jTextFieldNP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDP)
                    .addComponent(jTextFieldDP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelVP)
                    .addComponent(jTextFieldVP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelQ))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTP)
                    .addComponent(jTextFieldPT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelNF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldNF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCadastrarProd)
                    .addComponent(jButtonCancelarProd))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCadastrarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarProdActionPerformed
         String codigo = jTextFieldCP.getText();
         String nome = jTextFieldNP.getText();
         String descricao = jTextFieldDP.getText();
         String valor = jTextFieldVP.getText();
         String tipo = jTextFieldPT.getText();
         String nf = jTextFieldNF.getText();
         String quantidade = jTextFieldQ.getText();
         
         
         Fornecedores fornecedores = new Fornecedores(valor, nome, nf, endereco, tipo, nf);
       
        
         produtosDao p = new produtosDao();
         Produtos produtos = new Produtos(WIDTH, nome, descricao, null, Double.NaN, tipo, fornecedores);
         
         p.addProdutos(produtos);
      
        jTextFieldCP.setText("");
        jTextFieldNP.setText("");
         
    }//GEN-LAST:event_jButtonCadastrarProdActionPerformed

    private void jButtonCancelarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarProdActionPerformed
        int resposta = JOptionPane.showConfirmDialog(null, "Deseja realmente fechar?", "Mensagem de saída!", JOptionPane.YES_NO_OPTION);
        if(resposta == JOptionPane.YES_OPTION){
            this.dispose();
        }else{
            System.out.println(0);
            
        }
    }//GEN-LAST:event_jButtonCancelarProdActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadastrarProd;
    private javax.swing.JButton jButtonCancelarProd;
    private javax.swing.JLabel jLabelCP;
    private javax.swing.JLabel jLabelDP;
    private javax.swing.JLabel jLabelNF;
    private javax.swing.JLabel jLabelNP;
    private javax.swing.JLabel jLabelQ;
    private javax.swing.JLabel jLabelTP;
    private javax.swing.JLabel jLabelVP;
    private javax.swing.JTextField jTextFieldCP;
    private javax.swing.JTextField jTextFieldDP;
    private javax.swing.JTextField jTextFieldNF;
    private javax.swing.JTextField jTextFieldNP;
    private javax.swing.JTextField jTextFieldPT;
    private javax.swing.JTextField jTextFieldQ;
    private javax.swing.JTextField jTextFieldVP;
    // End of variables declaration//GEN-END:variables
}
