/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Luciana_2
 */
public class CadVendedor extends javax.swing.JInternalFrame {
    private Principal telaAnterior;

    /**
     * Creates new form CadVendedor
     */
    public CadVendedor() {
        initComponents();
    }

    public CadVendedor(Principal telaAnterior){
        this();
        //construtor
        this.telaAnterior = telaAnterior;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelNomeV = new javax.swing.JLabel();
        jTextFieldNomeV = new javax.swing.JTextField();
        jLabelCPFV = new javax.swing.JLabel();
        jTextFieldCPFV = new javax.swing.JTextField();
        jLabelRGV = new javax.swing.JLabel();
        jTextFieldRGV = new javax.swing.JTextField();
        jLabelNumV = new javax.swing.JLabel();
        jTextFieldBairroV = new javax.swing.JTextField();
        jLabelTelV = new javax.swing.JLabel();
        jTextFieldCV = new javax.swing.JTextField();
        jLabelRuaV = new javax.swing.JLabel();
        jTextFieldRuaV = new javax.swing.JTextField();
        jLabelBV = new javax.swing.JLabel();
        jTextFieldNumV = new javax.swing.JTextField();
        jLabelCEPV = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabelCV = new javax.swing.JLabel();
        jTextFieldCEPV = new javax.swing.JTextField();
        jTextFieldTelV = new javax.swing.JTextField();
        jLabelComplementoV = new javax.swing.JLabel();
        jLabelUFV = new javax.swing.JLabel();
        jTextFieldUFV = new javax.swing.JTextField();
        jButtonCadastrarV = new javax.swing.JButton();
        jButtonCancelarV = new javax.swing.JButton();

        setTitle("Cadastro de Vendedores");

        jLabelNomeV.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        jLabelNomeV.setText("* Nome Completo:");

        jTextFieldNomeV.setToolTipText("Informe o nome completo");

        jLabelCPFV.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        jLabelCPFV.setText("*CPF:");

        jTextFieldCPFV.setToolTipText("Informe o CPF");

        jLabelRGV.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        jLabelRGV.setText("RG:");

        jTextFieldRGV.setToolTipText("Informe o RG");

        jLabelNumV.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        jLabelNumV.setText("Número:");

        jTextFieldBairroV.setToolTipText("Informe o bairro");

        jLabelTelV.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        jLabelTelV.setText("Telefone:");

        jLabelRuaV.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        jLabelRuaV.setText("Rua:");

        jTextFieldRuaV.setToolTipText("Informe o nome da rua");

        jLabelBV.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        jLabelBV.setText("Bairro:");

        jLabelCEPV.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        jLabelCEPV.setText("CEP:");

        jTextField8.setToolTipText("Informe o complemento,se caso houver");

        jLabelCV.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        jLabelCV.setText("Cidade:");

        jTextFieldCEPV.setToolTipText("Informe o CEP");

        jLabelComplementoV.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        jLabelComplementoV.setText("Complemento:");

        jLabelUFV.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        jLabelUFV.setText("UF:");

        jTextFieldUFV.setToolTipText("Informe o estado");

        jButtonCadastrarV.setText("Cadastrar");
        jButtonCadastrarV.setToolTipText("Cadastrar");
        jButtonCadastrarV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarVActionPerformed(evt);
            }
        });

        jButtonCancelarV.setText("Cancelar");
        jButtonCancelarV.setToolTipText("cancelar cadastro");
        jButtonCancelarV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCPFV)
                            .addComponent(jTextFieldCPFV, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelRGV)
                            .addComponent(jTextFieldRGV)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelBV))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldTelV, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelTelV))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelCEPV)
                                .addGap(0, 76, Short.MAX_VALUE))
                            .addComponent(jTextFieldCEPV)))
                    .addComponent(jLabelNomeV)
                    .addComponent(jTextFieldNomeV, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelRuaV)
                            .addComponent(jTextFieldRuaV, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNumV)
                            .addComponent(jTextFieldNumV, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabelComplementoV)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(156, 156, 156)
                                .addComponent(jLabelCV))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextFieldBairroV, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldCV, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelUFV)
                            .addComponent(jTextFieldUFV, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(jButtonCadastrarV)
                .addGap(33, 33, 33)
                .addComponent(jButtonCancelarV)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelNomeV)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldNomeV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCPFV)
                    .addComponent(jLabelRGV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCPFV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldRGV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRuaV)
                    .addComponent(jLabelNumV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldRuaV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNumV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCEPV)
                    .addComponent(jLabelComplementoV)
                    .addComponent(jLabelTelV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldTelV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCEPV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCV)
                    .addComponent(jLabelBV)
                    .addComponent(jLabelUFV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldBairroV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldUFV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCadastrarV)
                    .addComponent(jButtonCancelarV))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCadastrarVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCadastrarVActionPerformed

    private void jButtonCancelarVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarVActionPerformed
        System.out.println("Fechar Aqui!");
        this.dispose();
        telaAnterior.setEnabled(false);
    }//GEN-LAST:event_jButtonCancelarVActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadastrarV;
    private javax.swing.JButton jButtonCancelarV;
    private javax.swing.JLabel jLabelBV;
    private javax.swing.JLabel jLabelCEPV;
    private javax.swing.JLabel jLabelCPFV;
    private javax.swing.JLabel jLabelCV;
    private javax.swing.JLabel jLabelComplementoV;
    private javax.swing.JLabel jLabelNomeV;
    private javax.swing.JLabel jLabelNumV;
    private javax.swing.JLabel jLabelRGV;
    private javax.swing.JLabel jLabelRuaV;
    private javax.swing.JLabel jLabelTelV;
    private javax.swing.JLabel jLabelUFV;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextFieldBairroV;
    private javax.swing.JTextField jTextFieldCEPV;
    private javax.swing.JTextField jTextFieldCPFV;
    private javax.swing.JTextField jTextFieldCV;
    private javax.swing.JTextField jTextFieldNomeV;
    private javax.swing.JTextField jTextFieldNumV;
    private javax.swing.JTextField jTextFieldRGV;
    private javax.swing.JTextField jTextFieldRuaV;
    private javax.swing.JTextField jTextFieldTelV;
    private javax.swing.JTextField jTextFieldUFV;
    // End of variables declaration//GEN-END:variables
}
